---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: files/img
public_path: "{{ site.baseurl }}/src/img"
front_matter_path: "/files/img"
use_front_matter_path: true
file_template: ":filename:"
